// ualbf-project/verification-lib/build.rs
// Cargo build script to generate verification_ffi.h from Rust FFI exports in src/lib.rs

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn map_rust_type_to_c(rust_type: &str) -> String {
    let t = rust_type.trim();
    if t == "*const std::ffi::c_char"
        || t == "*const c_char"
        || t == "*const i8"
        || t == "*const u8"
    {
        "const char*".to_string()
    } else if t == "*mut std::ffi::c_char" || t == "*mut c_char" || t == "*mut i8" || t == "*mut u8"
    {
        "char*".to_string()
    } else if t == "*const std::ffi::c_void" || t == "*const c_void" {
        "const void*".to_string()
    } else if t == "*mut std::ffi::c_void" || t == "*mut c_void" {
        "void*".to_string()
    } else if t == "*mut bool" {
        "bool*".to_string()
    } else if t == "*const bool" {
        "const bool*".to_string()
    } else if t == "usize" {
        "size_t".to_string()
    } else if t == "isize" {
        "ptrdiff_t".to_string()
    } else if t == "bool" {
        "bool".to_string()
    } else if t == "u8" {
        "uint8_t".to_string()
    } else if t == "u16" {
        "uint16_t".to_string()
    } else if t == "u32" {
        "uint32_t".to_string()
    } else if t == "u64" {
        "uint64_t".to_string()
    } else if t == "i8" {
        "int8_t".to_string()
    } else if t == "i16" {
        "int16_t".to_string()
    } else if t == "i32" {
        "int32_t".to_string()
    } else if t == "i64" {
        "int64_t".to_string()
    } else if t == "f32" {
        "float".to_string()
    } else if t == "f64" {
        "double".to_string()
    } else if let Some(stripped) = t.strip_prefix("*const ") {
        let inner = map_rust_type_to_c(stripped);
        format!("const {}*", inner)
    } else if let Some(stripped) = t.strip_prefix("*mut ") {
        let inner = map_rust_type_to_c(stripped);
        format!("{}*", inner)
    } else {
        t.to_string()
    }
}

fn parse_c_exports(content: &str) -> Vec<String> {
    let mut prototypes = Vec::new();
    let kw = "pub extern \"C\" fn ";

    let mut rest = content;
    while let Some(pos) = rest.find(kw) {
        let fn_start = pos + kw.len();
        rest = &rest[fn_start..];

        if let Some(paren_open) = rest.find('(') {
            let fn_name = rest[..paren_open].trim();
            if fn_name.is_empty() || !fn_name.chars().all(|c| c.is_alphanumeric() || c == '_') {
                continue;
            }

            let mut depth = 1;
            let mut paren_close = None;
            for (idx, ch) in rest[paren_open + 1..].char_indices() {
                if ch == '(' {
                    depth += 1;
                } else if ch == ')' {
                    depth -= 1;
                    if depth == 0 {
                        paren_close = Some(paren_open + 1 + idx);
                        break;
                    }
                }
            }

            if let Some(close_idx) = paren_close {
                let args_str = &rest[paren_open + 1..close_idx];
                let after_args = &rest[close_idx + 1..];

                let body_start = after_args.find('{').unwrap_or(after_args.len());
                let ret_part = after_args[..body_start].trim();

                let ret_c_type = if let Some(arrow_idx) = ret_part.find("->") {
                    let rust_ret = ret_part[arrow_idx + 2..].trim();
                    map_rust_type_to_c(rust_ret)
                } else {
                    "void".to_string()
                };

                let mut c_args = Vec::new();
                for arg in args_str.split(',') {
                    let arg_trimmed = arg.trim();
                    if arg_trimmed.is_empty() {
                        continue;
                    }
                    if let Some(colon_idx) = arg_trimmed.find(':') {
                        let arg_name = arg_trimmed[..colon_idx].trim();
                        let arg_type = arg_trimmed[colon_idx + 1..].trim();
                        let c_type = map_rust_type_to_c(arg_type);
                        c_args.push(format!("{} {}", c_type, arg_name));
                    }
                }

                let c_args_str = if c_args.is_empty() {
                    "void".to_string()
                } else {
                    c_args.join(", ")
                };

                prototypes.push(format!("{} {}({});", ret_c_type, fn_name, c_args_str));
            }
        }
    }

    prototypes
}

fn generate_header(prototypes: &[String]) -> String {
    let mut header = String::new();
    header.push_str(
        "/*\n * Auto-generated by verification-lib/build.rs. DO NOT EDIT DIRECTLY.\n */\n\n",
    );
    header.push_str("#ifndef VERIFICATION_FFI_H\n");
    header.push_str("#define VERIFICATION_FFI_H\n\n");
    header.push_str("#include <stdbool.h>\n");
    header.push_str("#include <stddef.h>\n");
    header.push_str("#include <stdint.h>\n\n");
    header.push_str("#ifdef __cplusplus\n");
    header.push_str("extern \"C\" {\n");
    header.push_str("#endif\n\n");

    for proto in prototypes {
        header.push_str(proto);
        header.push('\n');
    }

    header.push_str("\n#ifdef __cplusplus\n");
    header.push_str("}\n");
    header.push_str("#endif\n\n");
    header.push_str("#endif /* VERIFICATION_FFI_H */\n");
    header
}

fn write_header_if_changed(target_path: &Path, content: &str) -> std::io::Result<()> {
    if let Some(parent) = target_path.parent() {
        fs::create_dir_all(parent)?;
    }
    if target_path.exists() {
        if let Ok(existing) = fs::read_to_string(target_path) {
            if existing == content {
                return Ok(());
            }
        }
    }
    fs::write(target_path, content)
}

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let manifest_path = PathBuf::from(&manifest_dir);
    let lib_rs_path = manifest_path.join("src/lib.rs");

    println!("cargo:rerun-if-changed=src/lib.rs");
    println!("cargo:rerun-if-changed=build.rs");

    let lib_content = fs::read_to_string(&lib_rs_path)
        .unwrap_or_else(|e| panic!("Failed to read {}: {}", lib_rs_path.display(), e));

    let prototypes = parse_c_exports(&lib_content);
    let header_content = generate_header(&prototypes);

    // 1. Output to OUT_DIR
    if let Ok(out_dir) = env::var("OUT_DIR") {
        let out_path = PathBuf::from(out_dir).join("verification_ffi.h");
        write_header_if_changed(&out_path, &header_content)
            .unwrap_or_else(|e| panic!("Failed to write header to OUT_DIR: {}", e));
    }

    // 2. Output to verification-lib/include/verification_ffi.h
    let include_path = manifest_path.join("include/verification_ffi.h");
    write_header_if_changed(&include_path, &header_content)
        .unwrap_or_else(|e| panic!("Failed to write header to include dir: {}", e));

    // 3. Output to target/include/verification_ffi.h if target directory exists
    let target_include_path = manifest_path.join("../target/include/verification_ffi.h");
    let _ = write_header_if_changed(&target_include_path, &header_content);
}
